### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by ghost** [google/sg2im#18]
Have tried generating scenes using coco and vg . This is a very nice idea. However, the image quality is very bad , looks like not enough models exist here.    

Also, the noise is also being added in code. May I know the reason please.    

Is there any extension to it, as the current quality images being produced are good for old atari games but not for business.

**Comment by jcjohnson** [comment]
What do you mean by "noise is being added in code"? How else would you expect noise to be added?

This was a research project and not intended for business or production use.

**Comment by ghost** [comment]
Thanks for reply. I am wondering do we need to add noise? instead of random I add zeros and output seems same.  
Thanks for confirmation that project is no more being updated. I was planning to use it in business.

**Comment by jcjohnson** [comment]
The model is an example of a [generative adversarial network](https://en.wikipedia.org/wiki/Generative_adversarial_network); the mathematical formulation requires noise as input to the system so that the output can model a full probability distribution.

In this case I suspect that models suffer from mode collapse, and thus don't actually make much use of the noise.

Since this project is licensed under Apache-2.0 you can use this project for commercial purposes (subject to the constraints of the license) but you should have some realistic expectation about the results you will get since the project wasn't intended for business use.

**Comment by ghost** [comment]
Thanks @jcjohnson
